%PLOTS HRV

load('RESULTS')

% kruskalwallis(RESULTS.ECG.HRV.time.SDNN')
% kruskalwallis(RESULTS.ECG.HRV.time.RMSSD')
% kruskalwallis(RESULTS.ECG.HRV.time.pNN50')

% figure
% boxchart(RESULTS.ECG.HRV.time.SDNN', 'HandleVisibility','off')
% xticks(categorical([1 2 3 4 5 6]))
% xticklabels({'ME', 'MI', 'MIMO', 'MIMOVR', 'MIMOHP', 'MIMOVRHP'})
% title('Standard Deviation of NN intervals')
% hold on
% plot(RESULTS.ECG.HRV.time.SDNN, 'r.', 'HandleVisibility','off')
% plot(RESULTS.ECG.HRV.time.SDNN)
% legend("sub-01", "sub-02", "sub-03", "sub-04", "sub-05", "sub-06", "sub-07", ...
%     "sub-08", "sub-09", "sub-12", "sub-13", "sub-14", "sub-15", "sub-16", ...
%     "sub-17", "sub-18", "sub-19", "pilot-01", "pilot-02", "pilot-03", ...
%     'Location','bestoutside')
% xlabel('Condition')
% ylabel('Breaths Per Minute')
% ylim('padded')
% box on

% figure
% boxchart(RESULTS.PPG.HRV.time.SDNN', 'HandleVisibility','off')
% xticks(categorical([1 2 3 4 5 6]))
% xticklabels({'ME', 'MI', 'MIMO', 'MIMOVR', 'MIMOHP', 'MIMOVRHP'})
% title('Standard Deviation of NN intervals')
% hold on
% plot(RESULTS.ECG.HRV.time.SDNN, 'r.', 'HandleVisibility','off')
% plot(RESULTS.ECG.HRV.time.SDNN)
% legend("sub-01", "sub-02", "sub-03", "sub-04", "sub-05", "sub-06", "sub-07", ...
%     "sub-08", "sub-09", "sub-12", "sub-13", "sub-14", "sub-15", "sub-16", ...
%     "sub-17", "sub-18", "sub-19", "pilot-01", "pilot-02", "pilot-03", ...
%     'Location','bestoutside')
% xlabel('Condition')
% ylabel('Breaths Per Minute')
% ylim('padded')
% box on

median_hrv_ecg_metrics = [
    median(RESULTS.ECG.HR.vertically,'omitnan');
    median(RESULTS.ECG.HRV.time.NN_mean','omitnan');
    median(RESULTS.ECG.HRV.time.SDNN','omitnan');
    median(RESULTS.ECG.HRV.time.RMSSD','omitnan');
    median(RESULTS.ECG.HRV.time.pNN50','omitnan')*100;
    ]

% figure
% title('Percentage A')
% spider_plot(mean_hrv_metrics, ...
%     'AxesLabels', {'ME', 'MI', 'MIMO', 'MIMOHP', 'MIMOVR', 'MIMOVRHP'}, ...
%     'AxesWebType', 'circular', ...
%     'AxesDisplay', 'none', ...
%     'FillOption', 'on', ...
%     'FillTransparency', 0.1, ...
%     'AxesDisplay', 'data', ...
%     'AxesDataOffset', 0.1, ...
%     'AxesFontSize', 8)
% legend('NN','SDNN', 'RMSSD', 'pNN50')

figure('Name','ECG Percentage')
spider_plot(median_hrv_ecg_metrics', ...
    'AxesLabels', {{'HR';'(beats per minute)'}, {'NN'; '(ms)'}, ...
    {'SDNN';'(ms)'}, {'RMSSD';'(ms)'}, {'pNN50';'(%)'}}, ...
    'FillOption', 'on', ...
    'AxesWebType', 'circular', ...
    'FillTransparency', 0.05, ...
    'AxesDisplay', 'data', ...
    'AxesDataOffset', 0, ...
    'MarkerSize', 24, ...
    'AxesFontSize', 12, ...
    'LabelFontSize', 12, ...
    'AxesRadialLineWidth', 0.5, ...
    'AxesWebLineWidth', 0.5, ...
    'LineWidth', 1.5, ...
    'AxesDataOffset', 0.05)
legend('ME', 'MI', 'MIMO', 'MIMOHP', 'MIMOVR', 'MIMOVRHP', ...
    'FontSize', 12)

for i = 1:6
    percentage_difference(:,i) = median_hrv_ecg_metrics(:,i) - median_hrv_ecg_metrics(:,1)
end

% figure
% title('Percentage Difference A')
% spider_plot(percentage_difference(:,2:6), ...
%     'AxesLabels', {'MI', 'MIMO', 'MIMOHP', 'MIMOVR', 'MIMOVRHP'}, ...
%     'AxesWebType', 'circular', ...
%     'AxesDisplay', 'none', ...
%     'FillOption', 'on', ...
%     'FillTransparency', 0.1, ...
%     'AxesDisplay', 'data-percent', ...
%     'AxesDataOffset', 0.1, ...
%     'AxesFontSize', 8)
% legend('HR', 'NN', 'SDNN', 'RMSSD', 'pNN50')

figure('Name','ECG Percentage Change')
spider_plot(percentage_difference(:,1:6)'./100, ...
    'AxesLabels', {'HR', 'NN', 'SDNN', 'RMSSD', 'pNN50'}, ...
    'AxesWebType', 'circular', ...
    'AxesDisplay', 'none', ...
    'FillOption', {'off','on','on','on','on','on'}, ...
    'FillTransparency', 0.1, ...
    'AxesDisplay', 'data-percent', ...
    'AxesDataOffset', 0, ...
    'MarkerSize', 24, ...
    'AxesFontSize', 12, ...
    'LabelFontSize', 12,...
    'AxesRadialLineWidth', 0.5, ...
    'AxesWebLineWidth', 0.5, ...
    'LineWidth', 1.5, ...
    'AxesDataOffset', 0.05, ...
    'Color', [0,0,0; 0.85,0.325,0.098; 0.929,0.694,0.125; ...
    0.494,0.184,0.556; 0.466,0.674,0.188; 0.301,0.745,0.933 ], ...
    'LineStyle', {'--','-','-','-','-','-'}, ...
    'LineWidth', [1;1.5;1.5;1.5;1.5;1.5])
legend('MI', 'MIMO', 'MIMOHP', 'MIMOVR', 'MIMOVRHP', ...
    'FontSize', 12)


%%%%%%%%%%%%%%

% figure
% title('Percentage Difference B')
% spider_plot(percentage_difference(:,2:6)'./100, ...
%     'AxesLabels', {'HR', 'NN', 'SDNN', 'RMSSD', 'pNN50'}, ...
%     'AxesWebType', 'circular', ...
%     'AxesDisplay', 'none', ...
%     'FillOption', 'on', ...
%     'FillTransparency', 0.1, ...
%     'AxesDisplay', 'data-percent', ...
%     'AxesDataOffset', 0, ...
%     'MarkerSize', 24, ...
%     'AxesFontSize', 10, ...
%     'LineWidth', 0.25, ...
%     'AxesRadialLineWidth', 0.5, ...
%     'AxesWebLineWidth', 0.5)
% legend('MI', 'MIMO', 'MIMOHP', 'MIMOVR', 'MIMOVRHP', ...
%     'Location' ,'bestoutside')
% 
% 
% figure
% title('Percentage B')
% spider_plot(mean_hrv_metrics', ...
%     'AxesLabels', {{'HR';'(beats per minute)'}, {'NN'; '(ms)'}, ...
%     {'SDNN';'(ms)'}, {'RMSSD';'(ms)'}, {'pNN50';'(%)'}}, ...
%     'FillOption', 'on', ...
%     'AxesWebType', 'circular', ...
%     'FillTransparency', 0.1, ...
%     'AxesDisplay', 'data', ...
%     'AxesDataOffset', 0, ...
%     'MarkerSize', 24, ...
%     'AxesFontSize', 12, ...
%     'LineWidth', 0.25)
% legend('ME', 'MI', 'MIMO', 'MIMOHP', 'MIMOVR', 'MIMOVRHP', ...
%     'Location', 'bestoutside')

%%
%PPG PNN50 ONLY!!!!!!!!!!!!!

median_hrv_ppg_metrics = [
    median(RESULTS.PPG.HR.vertically,'omitnan');
    median(RESULTS.PPG.HRV.time.NN_mean','omitnan');
    median(RESULTS.PPG.HRV.time.pNN50','omitnan')*100;
    ]

figure('Name','ECG Percentage')
spider_plot(median_hrv_ppg_metrics', ...
    'AxesLabels', {{'HR';'(beats per minute)'}, {'NN'; '(ms)'}, {'pNN50';'(%)'}}, ...
    'FillOption', 'on', ...
    'AxesWebType', 'circular', ...
    'FillTransparency', 0.05, ...
    'AxesDisplay', 'data', ...
    'AxesDataOffset', 0, ...
    'MarkerSize', 24, ...
    'AxesFontSize', 12, ...
    'LabelFontSize', 12, ...
    'AxesRadialLineWidth', 0.5, ...
    'AxesWebLineWidth', 0.5, ...
    'LineWidth', 1.5, ...
    'AxesDataOffset', 0.05)
legend('ME', 'MI', 'MIMO', 'MIMOHP', 'MIMOVR', 'MIMOVRHP', ...
    'FontSize', 12)

for i = 1:6
    percentage_difference_ppg(:,i) = median_hrv_ppg_metrics(:,i) - median_hrv_ppg_metrics(:,1)
end

figure('Name','ECG Percentage Change')
spider_plot(percentage_difference_ppg(:,:)'./100, ...
    'AxesLabels', {'HR', 'NN', 'pNN50'}, ...
    'AxesWebType', 'circular', ...
    'AxesDisplay', 'none', ...
    'FillOption', {'off','on','on','on','on','on'}, ...
    'FillTransparency', 0.1, ...
    'AxesDisplay', 'data-percent', ...
    'AxesDataOffset', 0, ...
    'MarkerSize', 24, ...
    'AxesFontSize', 12, ...
    'LabelFontSize', 12,...
    'AxesRadialLineWidth', 0.5, ...
    'AxesWebLineWidth', 0.5, ...
    'LineWidth', 1.5, ...
    'AxesDataOffset', 0.05, ...
    'Color', [0,0,0; 0.85,0.325,0.098; 0.929,0.694,0.125; ...
    0.494,0.184,0.556; 0.466,0.674,0.188; 0.301,0.745,0.933 ], ...
    'LineStyle', {'--','-','-','-','-','-'}, ...
    'LineWidth', [1;1.5;1.5;1.5;1.5;1.5])
legend('MI', 'MIMO', 'MIMOHP', 'MIMOVR', 'MIMOVRHP', ...
    'FontSize', 12)